//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADDRESS()
        {
            this.CLIENT_ADDRESS = new HashSet<CLIENT_ADDRESS>();
        }
    
        public int ID_ADDRESS { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public string STREET { get; set; }
        public string NUMBER { get; set; }
        public string APARTMENT { get; set; }
        public string POSTCODE { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual ESTADO ESTADO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENT_ADDRESS> CLIENT_ADDRESS { get; set; }
    }
}
