//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_INS_PACK
    {
        public int ID_CAT_INS_PACK { get; set; }
        public Nullable<int> ID_CATERING { get; set; }
        public Nullable<int> ID_INSUMO { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> ID_PACKAGING { get; set; }
        public Nullable<int> ACTIVE { get; set; }
    
        public virtual CATERING CATERING { get; set; }
        public virtual INSUMO INSUMO { get; set; }
        public virtual PACKAGING PACKAGING { get; set; }
    }
}
