//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY_SUPPLIER
    {
        public int ID_CATEGORY_SUPPLIER { get; set; }
        public string NAME { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    }
}
