//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATERING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATERING()
        {
            this.CAT_INS_PACK = new HashSet<CAT_INS_PACK>();
            this.CATERING_INSUMO = new HashSet<CATERING_INSUMO>();
            this.CATERING_MENU = new HashSet<CATERING_MENU>();
            this.CATERING_PRODUCTO = new HashSet<CATERING_PRODUCTO>();
        }
    
        public int ID_CATERING { get; set; }
        public Nullable<int> ID_CLIENT { get; set; }
        public Nullable<int> ID_MENU { get; set; }
        public Nullable<int> AMOUNT_PEOPLE { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> EVENT_DATE { get; set; }
        public string NOTES { get; set; }
        public Nullable<bool> HAS_PARKING { get; set; }
        public string EVENT_TIME { get; set; }
        public Nullable<int> deleted { get; set; }
        public Nullable<int> ACTIVE { get; set; }
        public string DEPARTURE_TIME { get; set; }
        public string ARRIVAL_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_INS_PACK> CAT_INS_PACK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATERING_INSUMO> CATERING_INSUMO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATERING_MENU> CATERING_MENU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATERING_PRODUCTO> CATERING_PRODUCTO { get; set; }
        public virtual CLIENT CLIENT { get; set; }
        public virtual MENU MENU { get; set; }
    }
}
