//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATERING_PRODUCTO
    {
        public int ID_CATERING_PRODUCTO { get; set; }
        public Nullable<int> ID_CATERING { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<int> ACTIVE { get; set; }
    
        public virtual CATERING CATERING { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
