//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT_ADDRESS
    {
        public int ID_CLIENT_ADDRESS { get; set; }
        public Nullable<int> ID_CLIENT { get; set; }
        public Nullable<int> ID_ADDRESS { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<int> ACTIVE { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual CLIENT CLIENT { get; set; }
    }
}
