//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOM_UNIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOM_UNIT()
        {
            this.SUPPLIER_INSUMO = new HashSet<SUPPLIER_INSUMO>();
            this.USER_SUPPLIER_INSUMO = new HashSet<USER_SUPPLIER_INSUMO>();
        }
    
        public int ID_CUSTOM_UNIT { get; set; }
        public Nullable<int> ID_PORTIONED_BY { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    
        public virtual MEDIDA MEDIDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLIER_INSUMO> SUPPLIER_INSUMO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_SUPPLIER_INSUMO> USER_SUPPLIER_INSUMO { get; set; }
    }
}
