//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dishupEntities : DbContext
    {
        public dishupEntities()
            : base("name=dishupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADDRESS> ADDRESSes { get; set; }
        public virtual DbSet<CAT_INS_PACK> CAT_INS_PACK { get; set; }
        public virtual DbSet<CATEGORY_SUPPLIE> CATEGORY_SUPPLIE { get; set; }
        public virtual DbSet<CATEGORY_SUPPLIER> CATEGORY_SUPPLIER { get; set; }
        public virtual DbSet<CATERING> CATERINGs { get; set; }
        public virtual DbSet<CATERING_INSUMO> CATERING_INSUMO { get; set; }
        public virtual DbSet<CATERING_MENU> CATERING_MENU { get; set; }
        public virtual DbSet<CATERING_PRODUCTO> CATERING_PRODUCTO { get; set; }
        public virtual DbSet<CLIENT> CLIENTs { get; set; }
        public virtual DbSet<CLIENT_ADDRESS> CLIENT_ADDRESS { get; set; }
        public virtual DbSet<ESTADO> ESTADOes { get; set; }
        public virtual DbSet<INSUMO> INSUMOes { get; set; }
        public virtual DbSet<INSUMO_PACKAGING> INSUMO_PACKAGING { get; set; }
        public virtual DbSet<INSUMO_PACKAGING_PENDING> INSUMO_PACKAGING_PENDING { get; set; }
        public virtual DbSet<MEDIDA> MEDIDAs { get; set; }
        public virtual DbSet<MENU> MENUs { get; set; }
        public virtual DbSet<MENU_INSUMO> MENU_INSUMO { get; set; }
        public virtual DbSet<MENU_PRODUCTO> MENU_PRODUCTO { get; set; }
        public virtual DbSet<NOTIFICATION> NOTIFICATIONs { get; set; }
        public virtual DbSet<NOTIFICATION_TYPE> NOTIFICATION_TYPE { get; set; }
        public virtual DbSet<ORDER> ORDERS { get; set; }
        public virtual DbSet<ORDERS_ITEM> ORDERS_ITEM { get; set; }
        public virtual DbSet<PACKAGING> PACKAGINGs { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTOes { get; set; }
        public virtual DbSet<PRODUCTO_INSUMO> PRODUCTO_INSUMO { get; set; }
        public virtual DbSet<STOCK> STOCKs { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIERs { get; set; }
        public virtual DbSet<SUPPLIER_FILE> SUPPLIER_FILE { get; set; }
        public virtual DbSet<SUPPLIER_INSUMO> SUPPLIER_INSUMO { get; set; }
        public virtual DbSet<SUPPLIER_SUPPLIE> SUPPLIER_SUPPLIE { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<USER_INSUMO> USER_INSUMO { get; set; }
        public virtual DbSet<USER_SUPPLIER> USER_SUPPLIER { get; set; }
        public virtual DbSet<USER_SUPPLIER_INSUMO> USER_SUPPLIER_INSUMO { get; set; }
        public virtual DbSet<ALLERGEN> ALLERGENs { get; set; }
        public virtual DbSet<CATEGORY> CATEGORies { get; set; }
        public virtual DbSet<CATEGORY_TYPE> CATEGORY_TYPE { get; set; }
        public virtual DbSet<RECIPE> RECIPEs { get; set; }
        public virtual DbSet<RECIPE_DETAIL> RECIPE_DETAIL { get; set; }
        public virtual DbSet<CUSTOM_UNIT> CUSTOM_UNIT { get; set; }
    }
}
