//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSUMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSUMO()
        {
            this.CAT_INS_PACK = new HashSet<CAT_INS_PACK>();
            this.CATERING_INSUMO = new HashSet<CATERING_INSUMO>();
            this.INSUMO_PACKAGING = new HashSet<INSUMO_PACKAGING>();
            this.INSUMO_PACKAGING_PENDING = new HashSet<INSUMO_PACKAGING_PENDING>();
            this.MENU_INSUMO = new HashSet<MENU_INSUMO>();
            this.PRODUCTO_INSUMO = new HashSet<PRODUCTO_INSUMO>();
            this.PRODUCTO_INSUMO1 = new HashSet<PRODUCTO_INSUMO>();
            this.STOCKs = new HashSet<STOCK>();
            this.SUPPLIER_INSUMO = new HashSet<SUPPLIER_INSUMO>();
            this.SUPPLIER_SUPPLIE = new HashSet<SUPPLIER_SUPPLIE>();
        }
    
        public int ID_INSUMO { get; set; }
        public Nullable<int> ID_MEDIDA { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<decimal> WHOLESALE_PRICE { get; set; }
        public Nullable<decimal> SALE_PRICE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public string IMAGEN { get; set; }
        public Nullable<int> ID_CATEGORY_SUPPLIE { get; set; }
        public string PRODUCT_CODE { get; set; }
        public Nullable<int> ID_SUPPLIER { get; set; }
        public Nullable<decimal> PRICE_PER_UNIT { get; set; }
        public Nullable<bool> IS_PACKAGE { get; set; }
        public Nullable<bool> IS_PRODUCT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_INS_PACK> CAT_INS_PACK { get; set; }
        public virtual CATEGORY_SUPPLIE CATEGORY_SUPPLIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATERING_INSUMO> CATERING_INSUMO { get; set; }
        public virtual MEDIDA MEDIDA { get; set; }
        public virtual MEDIDA MEDIDA1 { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSUMO_PACKAGING> INSUMO_PACKAGING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSUMO_PACKAGING_PENDING> INSUMO_PACKAGING_PENDING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU_INSUMO> MENU_INSUMO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_INSUMO> PRODUCTO_INSUMO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_INSUMO> PRODUCTO_INSUMO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK> STOCKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLIER_INSUMO> SUPPLIER_INSUMO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLIER_SUPPLIE> SUPPLIER_SUPPLIE { get; set; }
    }
}
