//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_PRODUCTO
    {
        public int ID_MENU_PRODUCTO { get; set; }
        public Nullable<int> ID_MENU { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual MENU MENU1 { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual PRODUCTO PRODUCTO1 { get; set; }
    }
}
