//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_INSUMO
    {
        public int ID_MENU_INSUMO { get; set; }
        public Nullable<int> ID_MENU { get; set; }
        public Nullable<int> ID_INSUMO { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> ACTIVE { get; set; }
        public Nullable<int> ID_MEDIDA { get; set; }
    
        public virtual INSUMO INSUMO { get; set; }
        public virtual MEDIDA MEDIDA { get; set; }
        public virtual MENU MENU { get; set; }
    }
}
