//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION
    {
        public int ID_NOTIFICATION { get; set; }
        public string TITLE { get; set; }
        public Nullable<int> ID_NOTIFICATION_TYPE { get; set; }
        public string CONTROLLER { get; set; }
        public string ACTION { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    
        public virtual NOTIFICATION_TYPE NOTIFICATION_TYPE { get; set; }
    }
}
