//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.ORDERS_ITEM = new HashSet<ORDERS_ITEM>();
        }
    
        public int ID_ORDER { get; set; }
        public Nullable<int> ID_SUPPLIER { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<bool> DELIVERED { get; set; }
        public Nullable<bool> IS_DRAFT { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    
        public virtual SUPPLIER SUPPLIER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS_ITEM> ORDERS_ITEM { get; set; }
    }
}
