//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS_ITEM
    {
        public int ID_ORDER_ITEM { get; set; }
        public Nullable<int> ID_ORDER { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public string NOTES { get; set; }
        public Nullable<int> ACTIVE { get; set; }
        public Nullable<int> ID_SUPPLIER_INSUMO { get; set; }
    
        public virtual ORDER ORDER { get; set; }
        public virtual SUPPLIER_INSUMO SUPPLIER_INSUMO { get; set; }
    }
}
