//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.CATERING_PRODUCTO = new HashSet<CATERING_PRODUCTO>();
            this.MENU_PRODUCTO = new HashSet<MENU_PRODUCTO>();
            this.MENU_PRODUCTO1 = new HashSet<MENU_PRODUCTO>();
            this.PRODUCTO_INSUMO = new HashSet<PRODUCTO_INSUMO>();
            this.PRODUCTO_INSUMO1 = new HashSet<PRODUCTO_INSUMO>();
        }
    
        public int ID_PRODUCTO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> ES_COMBO { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<decimal> WHOLESALE_PRICE { get; set; }
        public Nullable<decimal> SALE_PRICE { get; set; }
        public string PESO_UNIDADES { get; set; }
        public string IMAGEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATERING_PRODUCTO> CATERING_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU_PRODUCTO> MENU_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU_PRODUCTO> MENU_PRODUCTO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_INSUMO> PRODUCTO_INSUMO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_INSUMO> PRODUCTO_INSUMO1 { get; set; }
    }
}
