//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_INSUMO
    {
        public int ID_PRODUCTO_INSUMO { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<int> ID_INSUMO { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> ID_MEDIDA { get; set; }
        public Nullable<int> ID_USER_SUPPLIER_INSUMO { get; set; }
    
        public virtual INSUMO INSUMO { get; set; }
        public virtual INSUMO INSUMO1 { get; set; }
        public virtual MEDIDA MEDIDA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual PRODUCTO PRODUCTO1 { get; set; }
        public virtual USER_SUPPLIER_INSUMO USER_SUPPLIER_INSUMO { get; set; }
    }
}
