//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        public int ID_STOCK { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<int> MINIMUM_AMOUNT { get; set; }
        public Nullable<int> CURRENT_AMOUNT { get; set; }
        public Nullable<int> MAX_AMOUNT { get; set; }
        public Nullable<int> ACTIVE { get; set; }
        public Nullable<int> ID_INSUMO { get; set; }
    
        public virtual INSUMO INSUMO { get; set; }
    }
}
