//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER_FILE
    {
        public int ID_SUPPLIER_FILE { get; set; }
        public Nullable<int> ID_SUPPLIER { get; set; }
        public string RUTA { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
