//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUPPLIER()
        {
            this.INSUMOes = new HashSet<INSUMO>();
            this.ORDERS = new HashSet<ORDER>();
            this.SUPPLIER_FILE = new HashSet<SUPPLIER_FILE>();
            this.SUPPLIER_INSUMO = new HashSet<SUPPLIER_INSUMO>();
            this.SUPPLIER_SUPPLIE = new HashSet<SUPPLIER_SUPPLIE>();
            this.USER_SUPPLIER = new HashSet<USER_SUPPLIER>();
        }
    
        public int ID_SUPPLIER { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string MOBILE_NUMBER { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string ABN_NUMBER { get; set; }
        public string ACN_NUMBER { get; set; }
        public string EMAIL { get; set; }
        public string OPEN_HOURS { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string DELIVERY_DAYS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSUMO> INSUMOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLIER_FILE> SUPPLIER_FILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLIER_INSUMO> SUPPLIER_INSUMO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLIER_SUPPLIE> SUPPLIER_SUPPLIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_SUPPLIER> USER_SUPPLIER { get; set; }
    }
}
