//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER_INSUMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUPPLIER_INSUMO()
        {
            this.ORDERS_ITEM = new HashSet<ORDERS_ITEM>();
            this.USER_INSUMO = new HashSet<USER_INSUMO>();
            this.USER_SUPPLIER_INSUMO = new HashSet<USER_SUPPLIER_INSUMO>();
        }
    
        public int ID_SUPPLIER_INSUMO { get; set; }
        public Nullable<int> ID_SUPPLIER { get; set; }
        public Nullable<int> ID_INSUMO { get; set; }
        public bool SELECTED { get; set; }
        public bool ACTIVE { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<bool> IS_PACKAGE { get; set; }
        public Nullable<int> ID_MEDIDA_PACKAGE { get; set; }
        public Nullable<int> QUANTITY_PACKAGE { get; set; }
        public Nullable<bool> IS_BOX { get; set; }
        public Nullable<int> QUANTITY_BOX { get; set; }
        public string NAME { get; set; }
        public Nullable<int> ID_CATEGORY_SUPPLIE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> ID_CUSTOM_UNIT { get; set; }
        public Nullable<decimal> INDIVIDUAL_PRICE { get; set; }
    
        public virtual INSUMO INSUMO { get; set; }
        public virtual MEDIDA MEDIDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS_ITEM> ORDERS_ITEM { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_INSUMO> USER_INSUMO { get; set; }
        public virtual CATEGORY_SUPPLIE CATEGORY_SUPPLIE { get; set; }
        public virtual CUSTOM_UNIT CUSTOM_UNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_SUPPLIER_INSUMO> USER_SUPPLIER_INSUMO { get; set; }
    }
}
