//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SUPPLIER_INSUMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_SUPPLIER_INSUMO()
        {
            this.RECIPE_DETAIL = new HashSet<RECIPE_DETAIL>();
            this.PRODUCTO_INSUMO = new HashSet<PRODUCTO_INSUMO>();
        }
    
        public int ID_USER_SUPPLIER_INSUMO { get; set; }
        public Nullable<int> ID_USER_SUPPLIER { get; set; }
        public string ID_USER { get; set; }
        public Nullable<int> ID_CATEGORY_SUPPLIE { get; set; }
        public Nullable<int> ID_MEDIDA_PACKAGE { get; set; }
        public string NAME { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<bool> IS_PACKAGE { get; set; }
        public Nullable<int> QUANTITY_PACKAGE { get; set; }
        public Nullable<bool> IS_BOX { get; set; }
        public Nullable<int> QUANTITY_BOX { get; set; }
        public bool SELECTED { get; set; }
        public bool ACTIVE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> ID_CUSTOM_UNIT { get; set; }
        public Nullable<decimal> INDIVIDUAL_PRICE { get; set; }
        public Nullable<decimal> UNIT_WEIGHT { get; set; }
        public Nullable<bool> IS_IMPORTED { get; set; }
        public Nullable<int> ID_SUPPLIER_INSUMO { get; set; }
    
        public virtual CATEGORY_SUPPLIE CATEGORY_SUPPLIE { get; set; }
        public virtual MEDIDA MEDIDA { get; set; }
        public virtual MEDIDA MEDIDA1 { get; set; }
        public virtual USER_SUPPLIER USER_SUPPLIER { get; set; }
        public virtual USER_SUPPLIER USER_SUPPLIER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECIPE_DETAIL> RECIPE_DETAIL { get; set; }
        public virtual CUSTOM_UNIT CUSTOM_UNIT { get; set; }
        public virtual SUPPLIER_INSUMO SUPPLIER_INSUMO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_INSUMO> PRODUCTO_INSUMO { get; set; }
    }
}
