//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_INSUMO
    {
        public int ID_USER_INSUMO { get; set; }
        public string ID_USER { get; set; }
        public Nullable<int> ID_SUPPLIER_INSUMO { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual SUPPLIER_INSUMO SUPPLIER_INSUMO { get; set; }
    }
}
